# 1. Vector and Matrix

## 1-1. Import numpy library
You can execute with "shift" + "return" key with the cursor displayed in the cell (inside the gray square). Since we only read libraries here, the result is not displayed in particular.

In [1]:
import numpy as np

## 1-2. Define vector
Define the vector $\mathbf{a}$ with the `np.array` command and display it with the `print` command. Let's change the numbers of elements of the vector in various ways.

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


## 1-3. The four (arithmetic) operations of vectors
The vector $\mathbf{a}$ plus 3 is the vector $\mathbf{b}$. Furthermore, we multiply the vector $\mathbf{b}$ by 10 times as the vector $\mathbf{c}$. Let's try other four arithmetic calculations.

In [3]:
b = a + 3
print(b)

[4 5 6]


In [4]:
c = b * 10
print(c)

[40 50 60]


## 1-4. Define matrix

Define matrices $\mathbf{D}$ and $\mathbf{E}$.

$
\mathbf{D} =
\begin{bmatrix} 1 & 2 & 4 \\ 3 & 5 & 7 \end{bmatrix}
$,
$
\mathbf{E} =
\begin{bmatrix} 3 & 4 \\ 5 & 6 \\ 5 & 4 \end{bmatrix}
$

Let's create a larger matrix (large number of rows and large number of columns) with reference to the examples of $\mathbf{D}$ and $\mathbf{E}$.

In [5]:
D = np.array( [[1,2,4], [3,5,7]] )
print(D)

[[1 2 4]
 [3 5 7]]


In [6]:
E = np.array( [[3,4], [5,6], [5,4]] )
print(E)

[[3 4]
 [5 6]
 [5 4]]


## 1-5. Inner product of matrix
Use the `np.dot` command to calculate the dot product of a matrix or vector. The vector $\mathbf{z}$ is the inner product of the matrix $\mathbf{X}$ and the vector $\mathbf{y}$.

$
\mathbf{z} = \mathbf{X} \cdot \mathbf{y} =
\begin{bmatrix} 1 & 3 \\ 5 & 7 \\ 9 & 11 \end{bmatrix} \cdot
\begin{bmatrix} 11 \\ 22 \end{bmatrix}
$

In [7]:
X = np.array( [[1,3], [5,7], [9,11]] )
y = np.array( [11,22] )
z = np.dot(X, y)
print(X)
print(y)
print(z)

[[ 1  3]
 [ 5  7]
 [ 9 11]]
[11 22]
[ 77 209 341]


## 1-6. Matrix elements and shapes
- Elements of a matrix can be specified with square brackets. The index starts from zero. Let's display numbers of different elements
- The matrix size (number of rows, number of columns) is returned by adding `.shape` to the matrix

In [8]:
print(X[0])
print(X[0][1])
print(X.shape)

[1 3]
3
(3, 2)
