# 1. ベクトルと行列

## 1-1. numpyライブラリを読み込む
実行したいセル(灰色の四角の中)にカーソルを表示させた状態で、「シフト」＋「リターン」キーで実行できます。なお、ここではライブラリを読み込むだけなので、特に結果は表示されません。

In [1]:
import numpy as np

## 1-2. ベクトルの定義
`np.array`コマンドでベクトル$\mathbf{a}$を定義し、`print`コマンドで表示します。ベクトルの要素の数字をいろいろと変えてみましょう。

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


## 1-3. ベクトルの四則計算
ベクトル$\mathbf{a}$に3を足したものをベクトル$\mathbf{b}$とします。さらにベクトル$\mathbf{b}$を10倍したものをベクトル$\mathbf{c}$とします。他の四則計算も試してみましょう。

In [3]:
b = a + 3
print(b)

[4 5 6]


In [4]:
c = b * 10
print(c)

[40 50 60]


## 1-4. 行列の定義

行列$\mathbf{D}$と$\mathbf{E}$を定義します。

$
\mathbf{D} =
\begin{bmatrix} 1 & 2 & 4 \\ 3 & 5 & 7 \end{bmatrix}
$,
$
\mathbf{E} =
\begin{bmatrix} 3 & 4 \\ 5 & 6 \\ 5 & 4 \end{bmatrix}
$

$\mathbf{D}$や$\mathbf{E}$の例を参考に、もっと大きな行列(行数や列数が大きい)を作ってみましょう。

In [5]:
D = np.array( [[1,2,4], [3,5,7]] )
print(D)

[[1 2 4]
 [3 5 7]]


In [6]:
E = np.array( [[3,4], [5,6], [5,4]] )
print(E)

[[3 4]
 [5 6]
 [5 4]]


## 1-5. 行列の内積
`np.dot`コマンドによって行列やベクトルの内積を計算します。ベクトル$\mathbf{z}$は行列$\mathbf{X}$とベクトル$\mathbf{y}$の内積となります。

$
\mathbf{z} = \mathbf{X} \cdot \mathbf{y} =
\begin{bmatrix} 1 & 3 \\ 5 & 7 \\ 9 & 11 \end{bmatrix} \cdot
\begin{bmatrix} 11 \\ 22 \end{bmatrix}
$

In [7]:
X = np.array( [[1,3], [5,7], [9,11]] )
y = np.array( [11,22] )
z = np.dot(X, y)
print(X)
print(y)
print(z)

[[ 1  3]
 [ 5  7]
 [ 9 11]]
[11 22]
[ 77 209 341]


## 1-6. 行列の要素と形
- カギ括弧で行列の要素を指定できます。インデックスはゼロから始まります。違う要素の数字を表示させてみましょう
- 行列に`.shape`を付けることで行列の大きさ(行数、列数)が返されます

In [8]:
print(X[0])
print(X[0][1])
print(X.shape)

[1 3]
3
(3, 2)
